services:
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      #- JWT_ENABLED=true
      #- JWT_SECRET=secret
      #- JWT_HEADER=Authorization
      #- JWT_IN_BODY=true
    # expose:
      # - '80'
      # - '443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    # volumes:
       # - /var/www/onlyoffice/Data
       # - /var/log/onlyoffice
       # - /var/lib/onlyoffice/documentserver/App_Data/cache/files
       # - /var/www/onlyoffice/documentserver-example/public/files
       # - /usr/share/fonts
    networks:
      - frontend
      - onlyoffice

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.onlyoffice_$ROUTER_NAME.tls.certresolver=myresolver"
      - "traefik.http.routers.onlyoffice_$ROUTER_NAME.rule=Host(`onlyoffice.$DOMAIN`)"
      - "traefik.http.services.onlyoffice_$ROUTER_NAME.loadbalancer.server.port=80"
      
      - "traefik.http.routers.onlyoffice_$ROUTER_NAME.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice_$ROUTER_NAME.middlewares=onlyoffice-https-redirect_$ROUTER_NAME"
      - "traefik.http.middlewares.onlyoffice-https-redirect_$ROUTER_NAME.redirectscheme.scheme=https"

      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice_custom_header_$ROUTER_NAME"
      - "traefik.http.middlewares.onlyoffice_custom_header_$ROUTER_NAME.headers.customResponseHeaders.Strict-Transport-Security=max-age=15552000; includeSubDomains; preload;"
      - "traefik.http.middlewares.onlyoffice_custom_header_$ROUTER_NAME.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.onlyoffice_custom_header_$ROUTER_NAME.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.onlyoffice_custom_header_$ROUTER_NAME.headers.browserXssFilter=true"
      - "traefik.http.middlewares.onlyoffice_custom_header_$ROUTER_NAME.headers.customRequestHeaders.X-Forwarded-Proto=https"
       
  onlyoffice-rabbitmq:
    image: rabbitmq
    restart: always
    # expose:
      # - '5672'
    networks:
      - onlyoffice

  onlyoffice-postgresql:
    image: postgres:12
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    # expose:
      # - '5432'
    # volumes:
      # - postgresql_data:/var/lib/postgresql
    networks:
      - onlyoffice
      
volumes:
  postgresql_data:


networks:
  frontend:
    external: true
  onlyoffice:
    internal: true

